apiVersion: batch/v1
kind: CronJob
metadata:
  name: spotify-auto-discovery-cronjob
  labels:
    app.kubernetes.io/name: spotify-auto-discovery-cronjob
spec:
  schedule: "0 8 * * 1"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: spotify-auto-discovery-kubernetes
            image: spotify-auto-discovery-kubernetes
            imagePullPolicy: Never
          restartPolicy: OnFailure