name: Github Scheduler
on:
  schedule:
    # - cron: '0 8 * * 1'
    - cron: '* * * * 4'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
    - name: Repo checkout
      uses: actions/checkout@v4
    # - name: Setup python
    #   uses: actions/setup-python@v5
    #   with:
    #     python-version: '3.10'
    #     cache: 'pip'
    - name: Install dependencies
      run: sudo pip install -r requirements.txt
    - name: Execute python script
      run: python3 main.py
      env: 
        SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
        SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
        SPOTIPY_REDIRECT_URI: ${{ secrets.SPOTIPY_REDIRECT_URI }}
        SPOTIFY_USER: ${{ secrets.SPOTIFY_USER }}
        DISCOVER_WEEKLY_ID: ${{ secrets.DISCOVER_WEEKLY_ID }}
